version: "3.7"

services:
  nginx_dev:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    #volumes:
      #- ./data:/data/db
    networks:
      - network

  app:
    build:
        context: .
        dockerfile: Dockerfile
    image: app
    container_name: app
    environment: 
      - MONGO_URI=mongodb://mongo:27017/cat-exam
      - REDIS_HOST=localhost
      - PORT=3000
      - REDIS_PORT=6379
    restart: always
    expose:
      - "3000"
    depends_on:
      - mongo
    networks:
      - network

networks:
  network:
    driver: bridge
